name: 'Develop'

on:
  push:
    branches:
      - 'master'

jobs:
  build-feature:
    runs-on: ubuntu-latest

    steps:

      - name: git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: build
        run: ./gradlew clean assemble

      - name: test
        run: ./gradlew check

      - name: sonar analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: build
        run: ./gradlew clean assemble

      - name: release
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET  }}
        run: ./gradlew publishPlugins
